# Generated by Django 5.2.5 on 2025-09-01 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'Superadmin'), ('AGENT', 'Agent'), ('SUBAGENT', 'Subagent'), ('CUSTOMER', 'Customer'), ('RIDERS', 'riders')], default='CUSTOMER', max_length=20),
        ),
    ]
