# Generated by Django 5.2.5 on 2025-08-28 16:27

import agents.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('location', models.CharField(default='Nairobi', max_length=200)),
                ('phone', models.CharField(blank=True, default='0714680792', max_length=20, null=True)),
                ('email', models.EmailField(blank=True, default='info@applemall.co.ke', max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New Agent', max_length=255)),
                ('phone', models.CharField(blank=True, default='0714680792', max_length=20, null=True)),
                ('email', models.EmailField(blank=True, default='agent@example.com', max_length=254, null=True)),
                ('reference_code', models.CharField(default=agents.models.generate_unique_reference, max_length=10)),
                ('is_shop', models.BooleanField(default=False)),
                ('commission_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_agents', to='agents.agent')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(max_length=50, unique=True)),
                ('sender_name', models.CharField(max_length=150)),
                ('receiver_name', models.CharField(max_length=255)),
                ('receiver_phone', models.CharField(default='0714680792', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('delivered', 'Delivered')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcels', to='agents.agent')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to='agents.shop')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
