# Generated by Django 5.2.5 on 2025-08-28 16:27

import agents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='reference_code',
            field=models.CharField(default=agents.models.generate_unique_reference, max_length=10, unique=True),
        ),
    ]
