# Generated by Django 5.2.5 on 2025-09-01 10:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0002_initial'),
        ('shops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parcel',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcels_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parcel',
            name='delivery_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='parcel',
            name='origin_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shops.shop'),
        ),
        migrations.AddField(
            model_name='parcel',
            name='payment_status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('TO_BE_PAID', 'To Be Paid')], default='TO_BE_PAID', max_length=20),
        ),
        migrations.AddField(
            model_name='parcel',
            name='payment_type',
            field=models.CharField(choices=[('FULL_AMOUNT', 'Full Amount'), ('DELIVERY_COST', 'Delivery Cost Only')], default='DELIVERY_COST', max_length=20),
        ),
        migrations.AddField(
            model_name='parcel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='via_matatu',
            field=models.BooleanField(default=False, help_text='Send directly to client (no shop).'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcels_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='CREATED', max_length=20),
        ),
    ]
