# Generated by Django 5.2.5 on 2025-09-01 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0003_parcel_created_at_parcel_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='full_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='parcel',
            name='matatu_direct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parcel',
            name='payment_method',
            field=models.CharField(choices=[('before_dispatch', 'Before Dispatch'), ('on_collection', 'On Collection')], default='on_collection', max_length=20),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], default='unpaid', max_length=20),
        ),
    ]
