# Generated by Django 5.2.5 on 2025-09-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0004_parcel_full_amount_parcel_matatu_direct_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcel',
            name='banner_image_url',
        ),
        migrations.AddField(
            model_name='parcel',
            name='dispatch_from',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='dispatch_to',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='customer_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='destination',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='matatu_direct',
            field=models.BooleanField(default=False, help_text='Was parcel dispatched directly via matatu?'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='payment_method',
            field=models.CharField(choices=[('BEFORE_DISPATCH', 'Before Dispatch'), ('ON_COLLECTION', 'On Collection'), ('CASH', 'Cash'), ('MPESA', 'M-Pesa'), ('BANK', 'Bank Transfer'), ('CARD', 'Credit/Debit Card'), ('NONE', 'Not Applicable')], default='ON_COLLECTION', max_length=20),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('partial', 'Partial')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('returned', 'Returned'), ('cancelled', 'Cancelled')], default='created', max_length=20),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='tracking_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
