# Generated by Django 5.2.5 on 2025-09-01 15:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0005_remove_parcel_banner_image_url_parcel_dispatch_from_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('parcel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_note', to='parcels.parcel')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('parcel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='parcels.parcel')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('receipt_number', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('partial', 'Partial')], default='pending', max_length=20)),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='parcels.parcel')),
            ],
        ),
    ]
