# Generated by Django 5.2.5 on 2025-09-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0006_deliverynote_invoice_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
