# Generated by Django 5.2.5 on 2025-09-01 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0007_receipt_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parcel',
            old_name='full_amount',
            new_name='amount',
        ),
    ]
