# Generated by Django 5.2.5 on 2025-09-01 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0008_rename_full_amount_parcel_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='Full_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
