# Generated by Django 5.2.5 on 2025-09-01 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0009_parcel_full_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parcel',
            old_name='Full_amount',
            new_name='full_amount',
        ),
    ]
