# Generated by Django 5.2.5 on 2025-09-01 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0011_parcel_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
