# Generated by Django 5.2.5 on 2025-09-01 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('earnings', '0001_initial'),
        ('parcels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agentdeliveryrecord',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agentdeliveryrecord',
            name='parcel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_records', to='parcels.parcel'),
        ),
        migrations.AddField(
            model_name='deliveryearning',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_earnings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliveryearning',
            name='parcel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='parcels.parcel'),
        ),
        migrations.AddField(
            model_name='subagentcommission',
            name='delivery_earning',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subagent_bonus', to='earnings.deliveryearning'),
        ),
        migrations.AddField(
            model_name='subagentcommission',
            name='parent_agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subagent_commissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subagentcommission',
            name='subagent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_commissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to=settings.AUTH_USER_MODEL),
        ),
    ]
